// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxANCKnCfX77Rkly2ixfk3Fsa2blXJDug',
    appId: '1:969067411112:web:6ab8d261713563cbf9b49d',
    messagingSenderId: '969067411112',
    projectId: 'zad-3cb78',
    authDomain: 'zad-3cb78.firebaseapp.com',
    storageBucket: 'zad-3cb78.firebasestorage.app',
    measurementId: 'G-4GSQVRRDCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTiOA_lrqll0RBKMhz_qZiP1xqb1tHVzY',
    appId: '1:969067411112:android:65b1a3f108b5409bf9b49d',
    messagingSenderId: '969067411112',
    projectId: 'zad-3cb78',
    storageBucket: 'zad-3cb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXG2S-RNKz1Mjuy4f41G6zk_pTpJXMHE',
    appId: '1:969067411112:ios:cfa74816db3ecba8f9b49d',
    messagingSenderId: '969067411112',
    projectId: 'zad-3cb78',
    storageBucket: 'zad-3cb78.firebasestorage.app',
    iosBundleId: 'com.zad.zad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyXG2S-RNKz1Mjuy4f41G6zk_pTpJXMHE',
    appId: '1:969067411112:ios:cfa74816db3ecba8f9b49d',
    messagingSenderId: '969067411112',
    projectId: 'zad-3cb78',
    storageBucket: 'zad-3cb78.firebasestorage.app',
    iosBundleId: 'com.zad.zad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxANCKnCfX77Rkly2ixfk3Fsa2blXJDug',
    appId: '1:969067411112:web:541cc33002dbd871f9b49d',
    messagingSenderId: '969067411112',
    projectId: 'zad-3cb78',
    authDomain: 'zad-3cb78.firebaseapp.com',
    storageBucket: 'zad-3cb78.firebasestorage.app',
    measurementId: 'G-HQLHPKS1MR',
  );
}
